### ISSUE TITLE
It doesn't apply corner radius?

### ISSUE THREAD

**Issue by hsleedevelop** [banxi1988/BXProgressHUD#1]
It doesn't apply corner radius?

After 1.6, BXProgressHud View is not apply corner radius?

**Comment by codetalks-new** [comment]
@evercry  Sorry for this breakup, I'll fix it in next version

**Comment by junhaiyang** [comment]
me too

**Comment by JamCode** [comment]
when will you fix it??

**Comment by codetalks-new** [comment]
Well, Finally, This Bug have been fixed. Sorry for such a long delay.
