### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by venkimohanraj** [banxi1988/BXProgressHUD#2]
Hi,
Do you have a version for Swift 3

**Comment by JamCode** [comment]
use pod install for Installing BXProgressHUD (1.8.0) failed

**Comment by codetalks-new** [comment]
@venkimohanraj  just released 2.0 (CocoaPods) for Swift 3
and source code is in swift3 branch

**Comment by venkimohanraj** [comment]
Thank you
